config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root "application#homepage"

  resources :videos, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_many :videos, dependent: :destroy
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :video_uuid, :provider, :url, presence: true

  scope :latest, -> { order(created_at: :desc) }

  delegate :email, to: :user, allow_nil: true, prefix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def homepage
    @videos = Video.includes(:user).latest.page(params[:page])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def create
    if User.find_by(email: sign_in_params[:email])
      self.resource = warden.authenticate!(auth_options)
      set_flash_message! :notice, :signed_in
    else
      self.resource = resource_class.new sign_in_params
      resource.save!
      set_flash_message! :notice, :signed_up
    end
    sign_in(resource_name, resource)
    respond_with resource, location: after_sign_in_path_for(resource)
  rescue => e
    flash[:alert] = e.message
    redirect_to root_path
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: :show

  def new
    @video = Video.new
  end

  def show
    @video = Video.find params[:id]
  end

  def create
    video_service = VideoService.new video_params[:url], current_user
    @video = video_service.call
    if @video.persisted?
      flash[:notice] = "Video shared successfully!!!"
      redirect_to @video
    else
      flash[:danger] = "Video share failed. Please try again!!!"
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit :url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/homepage.slim
.row.justify-content-center.u-mt50
  .col-md-10
    = render partial: "videos/video", collection: @videos
    = paginate @videos

app/views/layouts/_alerts.slim
.alert-message.mt-2
  - flash.each do |key, value|
    div class="alert alert-#{key}"
      - [value].flatten.each do |msg|
        p = msg

app/views/layouts/_footer.slim
footer.site-footer
  .container
    .row
      .col-md-6
        | Copyright © 2019 VideoShare. All rights reserved
      .col-md-6.text-md-right
        | Powered by VideoShare

app/views/layouts/_header.slim
nav.navbar.navbar-expand-lg.navbar-light.site-header
  .container
    a.navbar-brand href="/"  VideoShare
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      - if user_signed_in?
        .text.mr-sm-3
          = "Welcome, #{current_user.email}"
        = link_to "Share a video", new_video_path, class: "btn btn-success mr-sm-3"
        = link_to "Logout", destroy_user_session_path, method: :delete,
          class: "btn btn-outline-success"
      - else
        = form_with scope: :user, url: user_session_path, local: true,
          class: "form-inline my-2 my-lg-0" do |f|
          = f.email_field :email, placeholder: "Email",
            class: "form-control mr-sm-2", required: true
          = f.password_field :password, placeholder: "Password", required: true,
             pattern: ".{6,}", title: "Eight or more characters",
             class: "form-control mr-sm-2"
          = f.button "Login / Register", class: "btn btn-outline-success my-2 my-sm-0",
            type: "submit"

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Video Share
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta name="description" content="Share funny videos"
    meta name="keywords" content="video, share, youtube, twitter"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :stylesheet

    - if content_for?(:head)
      = yield(:head)
  body
    .turbolinks-progress-bar
    = render "layouts/header"
    main
      .container
        = render "layouts/alerts"
        = yield
    = render "layouts/footer"
    = yield :javascript

app/views/videos/_video.slim
.card
  .card-body
    .row
      .col-md-6
        .embed-responsive.embed-responsive-16by9
          iframe.embed-responsive-item src="https://www.youtube.com/embed/#{video.video_uuid}" allowfullscreen
      .col-md-6
        .text.text-large = link_to video.title, video_path(video)
        .text.text-small.text-river-bed
          span.mr-1 = "Shared by:"
          = video.user_email
        .text.mt-3 = video.description.truncate(300)

app/views/videos/new.slim
.row.justify-content-center.u-mt50
  .col-md-6
    .card
      h5.card-header.text-center Share a Youtube video
      .card-body
        = form_for @video do |f|
          .form-group
            = f.text_field :url, class: "form-control #{'is-invalid' if @video.errors.any?}",
              required: true, pattern: Settings.youtube_url_match,
              placeholder: "Enter the youtube video url you want to share"
            .invalid-feedback = "Please provide a valid youtube url."
          = f.button "Share", type: "submit", class: "btn btn-success btn-block"

app/views/videos/show.slim
.row.justify-content-center.u-mt50
  .col-md-10
    = render "video", video: @video